### ISSUE TITLE
Title bar is showing in a different color

### ISSUE THREAD

**Issue by pradeepcheers** [berlouz/glacier-dark-ui#1]
The title bar is showing in a different color.

<img width="817" alt="pastedgraphic-1" src="https://cloud.githubusercontent.com/assets/878734/21526336/59bdea64-cd1b-11e6-9004-ecc9896eae19.png">

I was expecting into be

![messages image 426774221](https://cloud.githubusercontent.com/assets/878734/21526381/9cf89fe0-cd1b-11e6-8af6-05bfe4a9ee8e.png)

**Comment by berlouz** [comment]
It's in your preferences that you have to change the configuration.
Link to help you:[https://github.com/atom-material/atom-material-ui/issues/334]( https://github.com/atom-material/atom-material-ui/issues/334)
